spring:
  datasource:
    url: jdbc:mariadb://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:clines}
    driverClassName: org.mariadb.jdbc.Driver
    username: ${DB_USER:cursos}
    password: ${DB_PASSWORD:cursos}
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: validate
      show-sql: true

cors:
  allowed:
    origins: http://localhost:3000
    all-methods: true
    all-headers: true
    send-credentials: true